[tool.poetry]
name = "nvim_venv"
version = "0.1.0"
description = ""
authors = ["Sumner Evans <me@sumnerevans.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pynvim = "^0.4.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
