theme = "slick"
icons = "awesome"

# Number of emails that are in my outbox, waiting to be sent.
[[block]]
block = "custom"
command = "echo  $(ls ~/.offlinemsmtp-outbox | wc -l)"
interval = 10

[[block]]
block = "maildir"
interval = 10
inboxes = [
    "/home/sumner/Mail/Mines/INBOX",
    "/home/sumner/Mail/Personal/INBOX",
    "/home/sumner/Mail/TEF/INBOX",
]
threshold_warning = 10
threshold_critical = 50

[[block]]
block = "music"
player = "spotify"
max_width = 25
buttons = ["prev", "play", "next"]

[[block]]
block = "memory"
format_mem = "{Mug}GiB"
format_swap = "{SUg}GiB"
warning_mem = 90
warning_swap = 90
critical_mem = 95
critical_swap = 95

[[block]]
block = "backlight"

[[block]]
block = "toggle"
text = "VPN"
command_state = "nmcli con show --active | grep 'Mines VPN' >/dev/null && echo 'VPN'"
command_on = "nmcli con up id 'Mines VPN'"
command_off = "nmcli con down id 'Mines VPN'"
interval = 5

[[block]]
block = "net"
device = "wlp4s0"
ssid = true
ip = true
speed_down = false
graph_down = false
speed_up = false
graph_up = false
interval = 5

[[block]]
block = "net"
device = "enp0s31f6"
ip = true
speed_down = false
graph_down = false
speed_up = false
graph_up = false
interval = 5

[[block]]
block = "sound"
step_width = 5

[[block]]
block = "time"
format = "%F %R:%S"
interval = 1

[[block]]
block = "battery"
interval = 30
format = "{percentage}% {time}"
device = "BAT0"

[[block]]
block = "battery"
interval = 30
format = "{percentage}% {time}"
device = "BAT1"
