#!/usr/bin/python3
from sig_helper import get_quote, print_contact_info

print("Sumner Evans")
print("2 Chronicles 7:14")
print()
print_contact_info()
print()
print("Note, this is not my main email, please update your contact information")
print("for me to my new email: me@sumnerevans.com.")
print()
print(get_quote())
