#!/usr/bin/python3
from sig_helper import get_quote

lines = [
    ("Jonathan Sumner Evans", "Instructor: CSCI 564"),
    ("https://sumnerevans.com", "CS@Mines Alumnus"),
    ("+1 (720) 459-1501", "M.S. Computer Science"),
    ("GPG: B50022FD", "Software Engineer @ The Trade Desk"),
]

print("\n".join("{:32}{}".format(*x) for x in lines))
print()
print(get_quote())
